CREATE TABLE IF NOT EXISTS users ( 
	user_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	profile VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS bookInfo (
	book_info_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(1024) NOT NULL,
	author VARCHAR(1024) NOT NULL,
	ISBN INT NOT NULL,
	last_edit_date DATETIME,
	editor_id BIGINT NOT NULL REFERENCES users
);

CREATE TABLE IF NOT EXISTS book ( 
	book_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	last_edited_info_id BIGINT NOT NULL REFERENCES bookInfo
);

CREATE TABLE IF NOT EXISTS comments ( 
	comment_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	target_book_id BIGINT NOT NULL REFERENCES book,
	edit_user_id BIGINT NOT NULL REFERENCES users,
	content VARCHAR(1024) NOT NULL,
	published_date DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS pastBookInfo(
	past_book_info_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	book_info_id BIGINT NOT NULL REFERENCES bookInfo,
	last_date DATETIME NOT NULL
);